### PR TITLE
Target separate homebrew repo

### PR DESCRIPTION
**Pull request by ryanwholey**
Moves the homebrew formula publish over to the new repo, [takescoop/homebrew-kubectl-exec-forward](https://github.com/takescoop/homebrew-kubectl-exec-forward). This will allow us to use `brew tap` directly without the additional repo URL

```diff
- brew tap takescoop/kubectl-exec-forward https://github.com/takescoop/kubectl-exec-forward.git
+ brew tap takescoop/kubectl-exec-forward
```

For the token, I'm thinking a new GitHub user, maybe `takescoop-oss`, and give the user access to the two repos.

### CODE REVIEW

**Comment by bendrucker** [comment]
Any reason to have the tap be specific to this tool as opposed to a company-wide formula repo?

Push can also be handled by deploy keys rather than bot users. Avoid machine users in GH where possible.

**Comment by ryanwholey** [comment]
Not sure deploy keys will work. I think goreleaser uses a token to auth for homebrew pushes, and a similar request was [dismissed](https://github.com/goreleaser/goreleaser/issues/2027) by the maintainers as a possible v2 milestone.

Re the company wide formula repo, happy to go this route if it will work! I can't find any docs stating that homebrew will look for a "base" repo in our org/user when searching for a tap, which is what I think we'd want for it to be worthwhile.

**Comment by ryanwholey** [comment]
Ah I think I just misunderstood how the tap works. So we might be able to do something like `takescoop/homebrew` which would containt he formula for `kubectl-forward-exec` and then push there?

```
brew tap takescoop/homebrew
brew install kubectl-forward-exec
```

**Comment by bendrucker** [comment]
A tap is a collection of formulas. That collection can be n=1 if you want but there's also the option to share and publish many formulas to a single tap. 

If the homebrew push is API based then look into GH apps:

https://github.com/marketplace/actions/github-app-token

Apps provided a clearer identity layer for managing programmatic access. Key differences are that apps also specify authorization, can be granted org wide, and more. You can't automate registration via the API but you can make as many apps as you want for specific purposes. Any admin can rotate the key themselves as opposed to logging in as an actual user. And it doesn't take license seats. 

Machine users on GitHub should be considered legacy, perhaps even to be reduced to zero in 2022.

**Comment by bendrucker** [comment]
Re taps, correct, and check on this convention but I think `homebrew-formulas` would be the ideal repo name. Clear as is and in the abbreviated `brew tap` form.

**Comment by ryanwholey** [comment]
neat! will look into that app -> token action there

**Comment by ryanwholey** [comment]
Okay I think we're setup:
- [Homebrew Releaser](https://github.com/organizations/TakeScoop/settings/apps/homebrew-releaser) GitHub app created and [installed](https://github.com/organizations/TakeScoop/settings/installations/21907283) with read/write to `takescoop/homebrew-formulas`
- Private key and app ID created as organization secrets, only added to `takescoop/kubectl-exec-forward` at the moment

New homebrew package repos would need to be added to the org secret allow list but other than that, they should be able to publish to homebrew-formulas without issue.

**Review by bendrucker — APPROVED** [review]
Awesome!

**Comment by ryanwholey** [comment]
Had to add `takescoop/kubectl-exec-forward` to the app's repo list, it was having trouble publishing the releases to this repo. (reran -> 🟢 )

**Pull request merged**
